#Minima by Tui
#
format = """
[ ](bg:transparent fg:{{colors.primary.default.hex}})\
$directory\
$git_branch\
$git_state\
$cmd_duration\
[ ](bg:transparent fg:{{colors.primary.default.hex}})\
[](bg:transparent fg:{{colors.primary.default.hex}})\
$time\
[ ](bg:transparent fg:{{colors.primary.default.hex}})\
$line_break\
$character"""

[directory]
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = "[ $path]($style)"

[directory.substitutions]
"~" = "  "
"Documents" = " 󰈙  "
"Downloads" = "   "
"Music" = "   "
"Pictures" = "   "
"Videos" = "   "
".config" = "   "

[character]
success_symbol = "[  ](bg:transparent fg:{{colors.primary.default.hex}})"
error_symbol = "[   ](bg:transparent fg:{{colors.error.default.hex}})"

[git_branch]
format = "[  $branch ]($style)"
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"

[git_state]
format = '\([$state($progress_current/$progress_total) ]($style)\)'
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"

[cmd_duration]
format = "[󰇘  󰔟$symbol $duration ]($style)"
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"

[time]
disabled = false
time_format = "%R"
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = '[󰥔 $time]($style)'